# Generated by Django 3.0.8 on 2020-07-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('github', models.CharField(max_length=255)),
                ('twitter', models.CharField(max_length=255)),
                ('linkedin', models.CharField(max_length=255)),
                ('facebook', models.CharField(max_length=255)),
                ('instagram', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
                ('picture', models.FileField(upload_to='')),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
